---
title: "小课04：也谈穆勒"
author: "石宇洋"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    self_contained: true
---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#809993"
)
```
class: inverse, center, middle

## 相对主义就是普遍的宽容

## 只是对不宽容者才不宽容

---
class: inverse, center, middle

# 原著阅读

### 你们要发誓没有下次
---
### 作业：亮点

#### 论自由
> 唯一名副其实的自由，是以我们自己的方式追求我们自身之善的自由，只要我们没有企图剥夺别人的这种自由，也不去阻止他们追求自由的努力。

#### 功利主义
> 他的理论却将“少数人”的幸福由主观变成了外界强加的客观，与前文对于幸福的定义产生了分歧。

---
### 作业：问题

* **逻辑链**：作者为什么写了A之后要写B

  * 作者行为的思路——成「链」而不是成「块」的
  
  * 深度，而非广度
  
  * 寻找逻辑链才能锻炼思维能力

* 从**思考问题**到**提出问题**

  > 如果只是一味思考已经被提出的问题，就无法得到「完全的自我」。道德哲学...提供了思考的工具，但没有提供议题。学会在讨论中逐渐...找到问题角度...条件限制...才能真正理性思考。
  
---
### “赘婿”文学热：当沉默的中年男人读起网络小说

吴明用一个星期写完了17篇“赘婿”故事大纲，赚了五万元人民币，然后因此压抑了一个月，“调动的都是负面情绪。”

赘婿文是中国大陆近两年最流行的网文类型，在今年7月份一系列以“歪嘴龙王”为名的改编视频广为流传后，它彻底走红。视频中，男主角入赘三年，每天洗衣、做饭，被妻子家族瞧不起，正当他被亲戚欺辱时，转机突然到来，原来过去的窝囊只是隐忍，男主角真正的身份是豪门少爷、或者权势滔天的龙王——那些妻子家族需要拼命讨好的大佬，见到男主角都立刻下跪。

在一篇典型的赘婿小说中，男主角在妻子家族里的形象长期是一个废物，每次崭露实力与身世，都出于各种原因不被妻子和她家人知晓，或者干脆遭遇更大的误会。在吴明卖出的那些“量产”故事大纲里，主线不是男主角实力的增长，而是逐渐获得妻子的认可——这是赘婿文独有的“爽点”，这与传统的男频网文（受众读者主要为男性）明显不同。

吴明从创作的角度把中国大陆网文的发展划分为三个世代，并将赘婿文置于最前沿的位置。第一代网文创造了无数幻想世界，出现了玄幻文、穿越文、游戏文、重生文等网文类型，读者的“爽”在天马行空的想像而非故事的打磨。第二代网文则回归现实世界，用读者现实生活中最熟悉的场景、人物、职业塑造强烈的代入感，满足读者的“爽点”。最典型如“兵王文”，主线是少年武道高手回归都市，成为校花的贴身保镖，凭借拳头横扫富家子弟和社会势力，并和美女白领、富家小姐、警花、护士、歌星等漂亮女性发生艳遇。

---
class: inverse, center, middle

# 道德

---
class: inverse, center, middle

# 道德建立在习俗之上吗？

---
### 道德建立在习俗之上吗？

>同情是种自然的情感...让我们不假思索地伸手援助我们看到的受苦者。——《人类不平等的起源和基础》，卢梭

>* 某种直觉性的道德感：对他人受苦的感受是与本能共存的...可以保证**普适性**。

> ****



>所谓我们自然的原则，只是我们习俗的原则...习俗只是因为是习俗而被遵守，而不是因为习俗是合理正当的——《沉思录》，巴斯卡

>* 习俗的多样性否决了道德原则的先验性。

> ****


>服从我的国家的法律与习俗...根据我要一起生活的人进行调整...世上没有东西会永远保持原本的状态...——《论方法》，笛卡尔

>* 要遵循既定的习俗和教育，但并不能受其蒙蔽。

> ****

> 尼采、马克思...

---
class: inverse, center, middle

# 他人是道德意识的基础吗？
---
### 他人（他者）是道德意识的基础吗？

>在别人面前昭然若揭的这个「谁」，他自己反而一直看不到。——《人的条件》，阿伦特

>* 人类的个体性（特点）在话语和行动者体现。每个人的独特性，在他与他人相处时才会显现。

> ****

>我建议你们以邻人之爱吗？我还宁可建议你们原理邻人以及对遥远者之爱！——《查拉图斯特拉如是说》，尼采

>* 爱那些并不存在的遥远者要胜过爱邻人。

> ****

>理性存在者乃作为目的自身而存在。——《道德形而上学基础》，康德

>* 他者是目的。


---
class: inverse, center, middle

# 合理的不平等是否存在？
---
### 合理的不平等是否存在？

>给更值得的人更多是合理的。——《尼各马可伦理学》，亚里士多德

>* 公平不是绝对严格的公平，而是合乎比例原则的公平。

> ****

>民主原则的败坏不仅发生在人们失去平等精神，还会发生在人们采取了极端平等的精神。——《论法的精神》，孟德斯鸠

>* 极端平等促使人民以平等之名否定政府与一切阶级。

> ****

>罗尔斯差异原则

>* 只有当「不平等」是有利于最弱势的人，以及不平等分配能够补偿有贡献的人时，才能接受这些「不平等」。

---
class: inverse, center, middle

# 道德规范允许有例外吗？

---
### 道德规范允许有例外吗？

>康德，《道德形而上学基础》

>* 道德若没有普遍规则，就毫无意义

> ****


>「审慎」是一种重要的德行...好好思虑并做出决定是明智者的主要功能。——《尼各马科伦理学》，亚里士多德

>* 应用道德时，必须根据可预期后果做出调整





<!-- pagedown::chrome_print("课件/02/02.Rmd") -->

<!-- 
可用案例：香港校本调查被推翻
https://theinitium.com/article/20201006-evening-brief/

-->











