---
title: "小课03：边沁功利主义 "
subtitle: "别期待生命无法给予的事物"
author: "石宇洋"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    self_contained: true
---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#809993"
)
```
### 作业：亮点

> 它是建立在苦乐原理的基础之上的，将人具有趋乐避苦的自然属性这一判断作为事实判断，并从这一点出发，认为增加幸福的事就是善的，应受到赞许，减少幸福的事是恶的，应受到非难。

# 

>但事实上，共同体功利最大化并不意味着每个共同体成员的功利最大化，不同群体间的利益存在矛盾与冲突。比如在本课案例中，对于湖河公司最优的选择是金刚砂公司刚开始就违约，但这样就没有任何产品生产出来，没有创造价值，并不符合社会功利最大化

# 

>在公共管理领域，每一项合法的公共政策都是出于集体的决策,而且一项政策的形成过程,实际上是各种利益群体和个人把自己的利益放到政策制定系统中,由政府对这一复杂多变的利益关系进行选择结合的结果。

---
### 作业：问题
* 作业：将原著阅读和案例分析放在一个word（或pdf）文档内（另：原著阅读在前），两篇文章之间换页

* 文件名：张三第四周2019010001

* 字数问题：「长」和「好」是两个概念

  * 本周零类文字数：1400+，一类文字数：600+-1600+，二类文字数：600+-800+
  
* 逻辑问题

* “存在即合理”

* 如果需要对作业提出建议，请在每周六中午十二点前上交作业，并在邮件主体部分告知我

* 作业分类标准：零类文（有亮点）、一类文（逻辑清晰）、二类文（逻辑基本清晰）、三类及以下

---
class: inverse, center, middle
# 随意打断我
---
class: nature, left, middle

### 请一定随意打断我

* 当你觉得我的逻辑存在漏洞（针对原著分析）

* 当你觉得案例分析有缺陷

...

---
class: nature, left, middle

# 边沁功利主义

---
class: nature, left, middle

### 重点

功利主义与利己主义

* 利己主义：强调个体功利最大化

* 功利主义：强调最大化最大多数人的幸福

边沁功利主义的「同质性」问题

* 快乐是可通约的

---
class: nature, left, middle

### 最大多数人的最大多数幸福


>By the principle of **utility** is meant that principle which approves or disapproves of every action whatsoever, according to the tendency which it appears to have to augment or diminish **the happiness of the party** whose interest is in question: or, what is the same thing in other words, to **promote or to oppose that happiness**.

---
class: nature, left, middle

### 道德的实然性与应然性问题

>Nature has placed mankind under the **governance** of two sovereign masters, pain and pleasure. It is for them alone to point out what we **ought to do**, as well as to **determine** what we **shall do**.

---
class: nature, left, middle

### TikTok
>2020年7月7日，美国国务卿迈克·蓬佩奥在接受福斯新闻频道主持人劳拉·英格拉汉姆采访时，表示中国的社交媒体应用**将用户的个人信息**交给中共政府，正考虑封杀，“尤其是TikTok”...美国总统唐纳德·特朗普向记者透露他计划最早于8月1日利用行政命令或其他手段**强制TikTok停止在美国的一切业务**...字节跳动则希望未来TikTok被收购后可以保留少量股权，不过美国总统唐纳德·特朗普反对收购，微软的收购谈判一度暂停，不过很快微软宣布重启收购计划。

>2020年8月3日，特朗普在白宫记者会上又声称，在9月15日前**TikTok必须要卖给美国公司**，否则将迫使其“关门大吉”...8月7日，美国总统特朗普签署两项行政命令，禁止受美国司法管辖的任何人或企业与TikTok的母公司字节跳动以及微信母公司腾讯进行任何交易。这两项命令于45天后生效。母公司字节跳动其后发表声明，表示将全力采取一切可行的措施，确保公司和用户获得公正的对待，如果美国政府不能给予公正对待，将诉诸美国法院...

---
class: nature, left, middle

### 「最大多数人」的最大多数幸福

>The interest of the community is one of the most general expressions that can occur in the phraseology morals...The community is a **fictitious** body, composed of **the individual persons who are considered as constituting as it were its members**.

---
class: nature, left, middle

### 最大多数人的「最大多数」幸福

《辛普森一家》与莎士比亚

吸毒问题

---
class: nature, left, middle

### 最大多数人的最大多数「幸福」

>By utility is meant that property in any object, whereby it tends to produce **benefit**, **advantage**, **pleasure**, **good** or **happiness**,(all this in the present case comes to the **same thing**) or...

---
class: inverse, center, middle

# 幸福
---
class: inverse, center, middle

# 幸福是幻觉吗？

---
class: nature, left, middle

### 幸福是幻觉吗？

>只有在我们的生活变成不幸时，我们才能首次首次感受到我们的生活曾经是幸福的。——《关于无意义与生命的痛苦》，叔本华

>* 幸福是某种稳定的状态，不同于简单的喜悦或是短暂的快乐...幸福要存在，就得不间断地持续下去...

> ****



>追逐幸福比幸福本身更加重要。——《沉思录》，巴斯卡

>* 我们所追求的，与其说是幸福，不如说是透过操心某事以忘记我们悲惨的处境。

> ****



>如果人们用「幸福」这个字眼去指某种持续的、最大程度令人喜悦的兴奋状态，这显然是无法实现之事...幸福的人生只有某些时刻是狂喜的，构成其存在的，是少数断续的痛苦，与大量多样的喜悦。——《功利主义》，密尔

>* 幸福并非与苦难和痛苦毫不相容。

---
class: inverse, center, middle

# 幸福是否取决我们自身？
---
class: nature, left, middle

### 幸福是否取决我们自身？

>我很少看见幸福的人，或许一个也没看过；但我经常看见满足的心灵，这是一切让我印象深刻的事物中最令我高兴的。——《孤独漫步者的沉思》，卢梭

>* 「幸福」与「满足」是不一致的

> ****



>如果你因为某种外在事物而感到痛苦，并不是此一事物让你烦乱不安，而是你对它所下的判断。——《沉思录》，奥里略

>* 必须区分取决于我们与不取决于我们的事物

> ****



>最好是不要那么高兴，而要有更多认识。——《哲学全集》，笛卡尔

>* 《逃避自由》

---
class: inverse, center, middle

# 道德高尚才能幸福吗？
---
class: nature, left, middle

### 道德高尚才能幸福吗？

> 幸福来自于...驱逐灵魂产生巨大昏乱的意见。——*Letter to Menoeceus*, Epicurus

> 一个具有理性和意志的存在，若其自然原有的目的就是他的保存、他的福祉。——《道德形而上学奠基》，康德

> ****


 
> 德行是幸福的结果。——《偶像的黄昏》，尼采

> 当一个民族毁灭、生理衰退的时候，由之产生的结果就是罪恶与奢侈。

---
class: inverse, center, middle  
# Q & A

---
class: inverse, center, middle  
# Thanks






<!-- pagedown::chrome_print("课件/02/02.Rmd") -->

<!-- 
可用案例：TikTok
https://cn.wsj.com/articles/%E7%BE%8E%E5%9B%BD%E6%B5%B7%E5%A4%96%E6%8A%95%E8%B5%84%E5%A7%94%E5%91%98%E4%BC%9A%E5%91%A8%E4%BA%8C%E5%B0%86%E5%AE%A1%E6%9F%A5%E7%94%B2%E9%AA%A8%E6%96%87%E4%B8%8Etiktok%E7%9A%84%E4%BA%A4%E6%98%93-11600212009

https://www.bbc.com/zhongwen/simp/business-54173718
-->










