---
title: "小课05：绝对律令"
subtitle: "而你只喜欢轻松愉快、游戏人生"
author: "洋子"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    self_contained: true
---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#D19379"
)
```
class: inverse, center, middle

# 康德
---
### 理性

.pull-left[
功利主义者定义

* 追求幸福减少痛苦的意志

* 算计幸福痛苦的能力
]

.pull-left[
康德

* 追求**善良意志**的**使命**

* 确定**义务**的能力
]

---
### 康德的反驳

如果我们的理性会用于追求功利

>总之,自然原本会防止理性在实践的运用中偏离方向,胆敢用它薄弱的洞察力为自己构想出获得幸福的计划和实现计划的手段来;自然自己原本不仅会选定目的,也会选定手段,而且会以明智的审慎**把这两者只托付给本能**。

>一个有教养的理性越是处心积虑地想得到生活的享受和幸福,那么这个人离真正的满足就越远,

>这些看法背后隐藏的根据是他们的实存之另一个更有价值得多的意图这一理念,理性的全部使命真正说来就在于这个意图,而不在于幸福

### 康德的理性

理性的目的在于追求**善良意志**

>理性就必定具有其真正的使命,这绝不是产生一个作为其他意图的手段的意志,而是产生一种自在的本身就善良的意志

>因为理性认识到自己最高的实践使命是.red[建立善良意志],它在实现这一意图时,只能按照自已特有的方式,也就是由于实现了一个仍然只由理性所规定的目的,而获得某种满足,哪怕这也许会和爱好的那些目的所遭受到的不少破坏联系在一起。

---
### 康德的要求

履行义务：普遍化法则

>那么我们愿意设想一下**义务**这个概念,这个概念包含了一个善良意志的概念,虽然处于某些主观的限制和障碍之下,但这些限制和障碍毕竟远不能把它掩盖起来,使它不被认识, 反而通过对比使它更为凸显,并且更加光辉灿烂

>那所剩下的就只是一般行动的普遍的合法则性,唯有这种合法则性才应该充当意志的原则,也就是说,**我绝不应当以其他方式行事,除非我也能够愿意我的准则果真成为一个普遍的法则**。

---
### 功利主义与康德主义

.pull-left[
**功利主义**

* 理性
  
  * 追寻幸福的能力
  
  * 计算幸福的能力
  
* 行为准则：幸福最大化

* 结果论
]


.pull-right[
**康德主义**

* 理性
  
  * 追求善良意志的使命
  
  * 辨析义务的能力
  
* 行为准则：履行义务

* 动机论
]

---
.pull-left[
### 动机论

> 并非出于爱好而是**出于义务**去增进自己的幸福,并且正是这样,他的行为才首次具有了真正的道德价值。

> 第二条原理是:一个出于义务的行动,其道德价值**不在于它所应当借此来实现的意图,而在于它据以被决定的准则**,因而也不取决于行动对象的实现,而仅仅取决于行动无关乎**欲求能力的任何对象而据以发生的意愿的原则**。

]

.pull-right[
### 结果论

仅以行为造成的**最终结果**评价行为本身

暂时不考虑**未来问题**
]

小贩的长远预期、社会凝视...

「堂吉柯德」


---
class: inverse, center, middle

# 绝对律令的推演

---
### 绝对律令的推演

.pull-left[
**普遍化与矛盾**

* C1：我可以许下我知道并不可能实现的诺言

* C2：普遍化——人人可以许下我知道并不可能实现的诺言

* P1：所有人都明白诺言可能是虚假的（且并不会受到道德谴责）

* P2：「诺言」不存在了
]

.pull-right[
**理性存在者作为目的**

* C1：我可以收养奴隶

* C2：理性本身是目的而非手段

**普遍化+理性目的一致**

* C1：我可以杀死我讨厌的人

* C2：普遍化——讨厌我的人可以杀死我

* P1：我与他人的目的有冲突
]

---
### 绝对律令的推演：尝试

简单的例子

* Statement 1：我可以在任何时候说谎（并最终得到他人信任）

* Statement 2：我可以无理由杀死对方

* Statement 3：我可以自杀


更难的例子

* 我可以发展婚外情

* 我可以在不开心的时候吸毒

* 我可以丢弃自己的孩子

* 我需要赡养父母

???
我可以在任何时候说谎（并最终得到他人信任）

* C1: 我可以无理由杀死对方 

* C2：普遍化——他人可以无理由杀死我 

* P1：我与他人的目的有冲突

我可以自杀

* C1: 我可以自杀 

* C2：理性本身是目的而非手段

---
class: inverse, center, middle

# 「道德」与「不道德」

# 「道德」与「非道德」

---
### 大胃王之“死”：当中国吃播背上浪费粮食的罪名

8月12日，央视新闻援引联合国粮农组织统计，称全球每年有三分之一的粮食被损耗和浪费，同时批评大胃王吃播秀，误导消费，浪费严重。8月23日，央视新闻第二次发声，再批畸形吃播为博流量胡吃海塞。

目前，中国国家网信办已对大胃王一类的吃播进行了精准监管，抖音、快手、微博、斗鱼等平台相继开始自检自控，删除和大胃王相关的内容，甚至封禁一些相关账号，并表示会继续严格抵制浪费粮食的行为，一经发现有违规行为，会严肃处理。现在，在用户搜索吃播等内容时，不少平台会跳出“珍惜粮食”，“拒绝浪费”等字样。

对大胃王的管控是近日中国政府号召节约粮食活动的第一部分，在此之前，政府下达政令，要求餐馆向顾客倡议“N-1点餐模式”，即有顾客吃饭点菜的数量需为“人数-1”。继性欲之后，食欲这一人们最原始和朴素的欲望，第一次被政府纳入一种系统性的管理之中。吃什么、吃多少、怎么吃成为了需要被再三审视和监控的内容。

有趣的是，这两种管控迎来了完全不同的回应：网友们对“N-1”模式大加嘲讽，但对大胃王的封禁却非常支持。不久前，中新经纬发起相关投票，询问网民对“大胃王吃播”的看法，35.1万微博网民参与了投票。其中，53.8%的网友认为可以接受吃播，但反对大胃王浪费粮食，还有34.2%的网友认为“难以理解吃播的意义是什么”。同时，昔日顶流的大胃王发的视频要么被删除，一些没有被删除的昔日视频也被新留言/弹幕“攻陷”，其中大多是批评甚至谩骂。大胃王们彻底迎来了行业发展中的至暗时刻。

???


1. 我们是否应该禁止「吃播」？

2. 我们是否应该推行「N-1点餐」?

3. 两者之间的目的是否一致？

4. 两者的影响是否一致？为何？
---
class: inverse, center, middle

# 自由





<!-- pagedown::chrome_print("课件/02/02.Rmd") -->

<!-- 
可用案例：香港校本调查被推翻
https://theinitium.com/article/20201006-evening-brief/

-->











