---
title: "小课08：无知之幕"
subtitle: "优先、限制与剥夺"
author: "洋子"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    self_contained: true
---
class: inverse, left, middle

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#939391"
)
```

##《像他们一样思考 你不可不知的十大思想家》

### 三联中读

---
class: inverse, left, middle

# 背景

---
class: left, middle

### 背景：罗尔斯的问题意识

一个自由民主的国家，应该是一个平等正义的国家，但为什么我们美国至今还存在着对黑人和少数族裔的歧视？

一个自由民主的国家，应该是一个爱好和平并坚定维护和平的国家。但我们美国为什么还要发动疯狂的对越战争？

一个自由民主的国家应该是充满希望的国家。但是为什么我们美国的年轻一代却如此的悲观、颓废，甚至绝望。


---
class: inverse, left, middle

# 《正义论》

---
### 《正义论》--解决问题：美国社会制度安排

.pull-left[
**功利主义目的论**

资本主义100年所创造的物质财富超过了以往一切时代的总和...但人们依然不满足

整个社会国家的财富总量、价值创造能力增长，但并不意味着这个国家所有的公民，所能够获取的待遇、分配的价值，就能够获得满足。

问题的根源不在于尽可能增长社会财富的总量来满足所有人，而是如何分配社会财富、社会价值。
]

.pull-right[
**社会道义论**

创立一种可普遍化的、适合于所有人的、以公平的正义为基础的社会道义论
]

---
class: left, middle

### 《正义论》--从目的论到道义论

根本问题：以**社会**的方式生存

* 人类的生物本性决定了人类是一种很脆弱的生物

* 人类为什么能从中脱颖而出，并且成为这个星球上的主人和看护者？

  * 一些脆弱的生命他们能够选择以社会的方式生成和发展
  
---
class: left, middle

### 社会的根本目的

福宁well-being 与 福利well-fare

### 社会的基本原则

自由与平等

---
class: left, middle

### 对传统社会契约论的改装

传统社会契约论

>在社会状态下要建立社会，每一个人对自我的自然本性就有所约束，要**放弃自己的一部分权利**，建成公权力，建立社会。这个过程应该基于自由和平等的基础来达成。那么基于社会状态以后，每个人的自由就不仅是天赋的，同时也是社会约定，依法，由国家《宪法》规定来赋予每一个人自由平等的权利。

社会普遍道义论

**无知之幕**、**利益无涉**与**良序社会**


---
class: left, middle

### 无知之幕

>最初人们在缔结社会的时候，每一个人都不去考虑**已有的或者既定的**那些差异、差别，仿佛每一个人的脸上都罩着一个纱巾。所谓“无知之幕”不是说我们人类无知，是我们知道彼此之间的差异，但是我们要缔结社会的时候，不能过多考虑你我的差异。如果考虑相互的差异，那诉求就不一样。 

> 特点：对自己一无所知；对其他知道的足够多；理性的、冷淡的
>
> 抹除：性别、肤色、天赋、利益、优势、劣势、社会、国家、自然环境……
>
> **参加社会合作**的人们在**平等的原初状态**下，一起选择将安排基本的权力义务和决定社会利益划分的原则

---
class: left, middle

### 利益无涉

>我们讨论的唯一目的是建立一个怎样的社会，才是对我们所有人都是最好的或是相对比较好的

---
class: inverse, left, middle

# 正义理论

---
### 正义理论

第一原则：平等的自由原则

* 第一层次：每一个社会成员都拥有平等的自由liberty权利

  * 宪法认同的自由有集会自由、结社自由、言论自由等等



第二原则：差异原则

* 第一层次：机会均等

> 罗尔斯“差异原则”的根本目的和用意，是消除差异，减少差异，寻求尽可能小的差异。

* 第二层次：社会的基本制度（有时用社会基本结构），尤其是分配制度，应有利于处于社会最不利地位的人。

---
class: left, middle

### 合法期望与道德应得

罗尔斯：没有道德应得，只有建立在社会制度上的合法期望。没有一个正义准则旨在奖赏德性。

---
### 两原则的张力

.center[**「正义的第一原则」要优先于「正义的第二原则」**

**词典式排序**]

正义的脆弱性

* 人生而平等--人生而不平等

* 「道德幸运」

* **规则**的代价

---

class: inverse, left, middle

## 考上清华？

---
class: inverse, left, middle


### 谢谢大家，下周见：）






