---
title: "小课07：自由至上及其背叛"
subtitle: "进步的速度可能是有破坏性的"
author: "洋子"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    self_contained: true
---
class: inverse, left, middle

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1D3052"
)
```
# 口试体验

---
### 备课会

从「个人」到「社会」？

* 从「如何去做」到「政府如何去做」


---
class: left, middle

# 作业

---
### 作业

1. 所有的问题都需要回到CTMR知识框架

2. 主体不适用问题

  * 康德的主体不适用问题

  * 功利主义的主体不存在问题

3. 规则功利主义与情景功利主义

4. 功利主义：可能考「成本——收益」分析（一定不考「快乐——痛苦」分析）


---


class: left, middle

# 诺齐克与康德

---
### [诺齐克与康德](https://iep.utm.edu/nozick/)

诺齐克认为他的政治哲学立足于康德的第二原则：**Act so that you treat humanity, whether in your own person or in that of another, always as an end and never as a means only**。人作为一个被赋予自我意识、自由意志和制定人生计划可能性的理性人，具有与生俱来的尊严，不能像无生命的物体那样，仅仅被当作一个单纯的东西、工具或资源。

诺齐克把人类个体描述为自我所有者（**self-owner**）——在政治哲学中至少可以追溯到约翰-洛克的概念：**个人拥有自己**--他们的身体、才能和能力、劳动，进而拥有他们行使才能、能力和劳动的成果或产品...（但是，自我所有权的论述实际上会确定奴隶制的非法性）

如果个人是不可侵犯的**目的**（如康德所描述的那样）和**自我所有者**，那么，诺齐克说，由此可见，他们有一定的权利，特别是（在这里再次追随洛克）对自己的生命、自由和劳动成果的权利。

**拥有自己就是拥有构成自己的各种要素的这种权利**。诺齐克说，这些权利的功能是对他人的行为进行侧面约束；它们对他人如何对待一个人设置了限制。因此，举例来说，既然你拥有自己，因而对自己有权利，那么别人在道德上就受到约束，不能杀害或残害你（因为这将涉及到破坏或损害你的财产），或绑架你或强行摘取你的一个身体器官移植到别人身上（因为这将涉及到偷取你的财产）。他们也受到约束，不能违背你的意愿强迫你为他人的目的工作，即使这些目的是好的。因为如果你拥有自己，那么你就有权决定是否以及如何使用你的自体及其权力，例如，要么工作，要么不工作。

---
### 洛克《政府论》

虽然这是自由的状态，却不是放任的状态。在这状态中，虽然人具有处理他的人身或财产的无限自由，但是他并**没有毁灭自身或他所占有的任何生物的自由**，除非有一种比单纯地保存它来得更高贵的用处要求将它毁灭。自然状态有一种为人人所应遵守的自然法对它起着支配作用；而**理性，也就是自然法，教导着有意遵从理性的全人类**：人们既然都是平等和独立的，任何人就不得侵害他人的生命、健康、自由或财产。因为既然人们都是全能和无限智慧的创世主的创造物，既然都是**唯一的最高主宰的仆人，奉他的命令来到这个世界，从事于他的事务，他们就是他的财产，是他的创造物，他要他们存在多久就存在多久**，而不由他们彼此之间作主；我们既赋有同样的能力，在同一自然社会内共享一切，就不能设想我们之间有任何从属关系，可使我们有权彼此毁灭，好像我们生来是为彼此利用的，如同低等动物生来是供我们利用一样。正因为每一个人必须保存自己，不能擅自改变他的地位，所以基于同样理由，当他保存自身不成问题时，他就应该尽其所能保存其余的人类，而除非为了惩罚一个罪犯，不应该夺去或损害另一个人的生命以及一切有助于保存另一个人的生命、自由、健康、肢体或物品的事物。

### 诺齐克《无政府、国家和乌托邦》

既然关于政治哲学和解释性政治理论的思考都汇聚于**洛克的自然状态**,那么我们也将从它开始。更准确地说,我们将从个人开始,而这些个人的处境与洛克的自然状态非常相似,以致可以对其许多重要差别忽略不计。只有当我们的概念与洛克的概念之间的某些歧异涉及政治哲学、涉及我们对国家的论证的时候,这些歧异才会被提到。

---
class: left, middle

# 《无政府、国家和乌托邦》

---

## 分配（持有）正义

论点：最低限度的国家是能够得到证明的最多功能的国家

* 用于反驳：「一种更多功能的国家得到了证明，因为它是为达到**分配正义**所必须的」

分配正义

* 定义：使用某种原则或标准来分发一些东西
  * 如果每一个人对该分配中所拥有的持有都是有资格的，那么一种分配就是正义的
    * 有资格：依据获取的正义原则、转让的正义原则得到
* 基础？：没有任何集中的分配，任何人/群体都没有资格控制所有资源，都没有资格共同决定如何分配
  * 总体结果是众多个人决定的产物，而所涉及的不同个人则有资格做出自己的决定
  
---

### 第一节：资格理论：两种资格（正义与矫正）

#### 持有的原初获取（获取的正义原则）

定义：对无主物的占有

#### 持有的转让（转让的正义原则）

定义：保障一种分配到另一种分配的过程合法

#### 持有不正义的矫正

---

### 历史原则与目的-结果原则

分配正义的资格理论是**历史**的

其他（例如功利主义、福利经济学）的正义是**即时**的

#### 模式化分配（的错误）

即：按照某种固定标准（道德功绩、智商...）进行分配

持有的状态一定不是模式化的

* 需要模式变项解释（i.e. 捐赠）

生产和分配是一体的

---
### 自由将打乱（模式化）的分配

* 不对人们的生活进行持续地干预，任何目的-结果原则或模式化的分配正义原则都不能得到持续的实现
* 个人权力是相互可能的
  * 阿玛蒂亚·森：社会排序不可能是线性的
    * 即：模式化是线性的，与个人自主相斥
  * 社会设定对象约束，而非决定排序

「持有」意味着「可以处置」这样一种权利

* 社会约束人们的处置方式，而非决定分配

---

### 洛克的获取理论

#### 持有的原初获取：某个人把他的劳动同无主物相混合mixing而产生的

限制条件：有足够多和同样好的（本来存在的）东西留给其他人共用

* 强化条件：1）失去改善机会；2）失去以前「可自由使用」的东西
* 弱化条件：1）失去改善机会

---
class:left, middle

# 《被检验的人生》

---

### 基础

《无政府、国家与乌托邦》：个人权利

《被检验的人生》：加入人道、团结

> 对价值之表达和象征的关切可以最好地和最突出地——更不用说有效的——以共同的和官方的方式（即以政治的方式）得到表达，而这种共同的和官方的关切则是对个人自我表达的关切的延续...我的意思不是说公共领域只是一件关于共同的自我表达的事情；我也希望通过它来实际上成就某种事业，来改变现状，而且，如果我们相信某些政策不会有助于帮助其他人和维持他们的生活，那么我们就会发现这些政策没有适当地表达与他们的团结。极端自由主义的观点只看政府的意图，不看它的意义，这样，它对意图也采取了过于狭隘的观点

> 这些其他人应该感受到——如果他们感受到了，那么他们会是更好的人——对公民同伴（以及对人类同伴，也许也对生物同伴）的关切和团结的纽带，尽管他们确实有权利不去感受这些。...然而，他们的公民同伴可以选择替他们说话，以掩饰缺乏关切和团结——无论人们自己是否认识到他们确实缺乏某种东西。替他们来掩饰，这样做或许是出于礼貌，或许是因为拥有对关切和团结的共同的公共认可对其他人很重要，如果只有通过这样做，他们才不会被迫注意到他们的某些同胞是多么冷漠和多么不人道。





